apiVersion: v1
kind: Service
metadata:
  name: config-spring-app
  labels:
    app: config-spring-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: config-spring-app
